import React from "react"
import "./globals.css"
import Navbar from "./components/Navbar"
import { getUser } from "../lib/state"
import CookieSetter from "./CookieSetter"
import { storage } from "../lib/directus"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log("DAT", JSON.stringify(storage.data));
  return (
    <html lang="en">
      <body>
        <CookieSetter cookie={JSON.stringify(storage.data)} />
        <Navbar user={getUser()} />
        {children}
      </body>
    </html>
  )
}
