const emoji: { [key: string]: string } = {
  rocket: "🚀",
  fire: "🔥",
  sparkle: "✨",
  star: "⭐",
  explosion: "💥",
  bomb: "💣",
  hammer: "🔨",
  lock: "🔒",
  key: "🔑",
  password: "🔐",
  tick: "✅",
  error: "❌",
  trash: "🗑️",
  hourglass: "⌛",
  hourglassDone: "⏳",
  debug: "🐞",
  magic: "🔮",
  eye: "👁️",
  eyes: "👀",
  ear: "👂",
  speaker: "🔊",
  mute: "🔇",
  sound: "🔉",
  music: "🎵",
  video: "🎥",
  camera: "📷",
  tv: "📺",
  computer: "💻",
  phone: "📱",
  fax: "📠",
  battery: "🔋",
  plug: "🔌",
  bulb: "💡",
  candle: "🕯️",
  flashlight: "🔦",
  paper: "📄",
  notebook: "📓",
  book: "📖",
  books: "📚",
  lockWithInkPen: "🔏",
  pen: "🖊️",
  paintbrush: "🖌️",
  crayon: "🖍️",
  pencil: "✏️",
  marker: "🖋️",
  scissors: "✂️",
  paperclip: "📎",
  link: "🔗"
};

export default emoji;
